---
title: # Predicting Housing Prices"
Authors: Scott Breitbach, Pushkar Chougule, & Rachel Nelson  
Class: DSC630-T301 Predictive Analytics (2221-1)
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(stats)
library(ggplot2)
library(class)
library(e1071)
library(FNN)
library(abind)
library(randomForest)
library(rpart)
library(cluster)
library(rattle)

```

## Modeling

```{r cars}
### RandomForest Model
train<-read.csv("dfTrain1.csv", header=TRUE)
test<-read.csv("dfTrain1.csv", header=TRUE)
y<-as.factor(train[,19])
x<-train[,4:18]
y_test<-as.factor(test[,19])
x_test<-test[,4:18]
fit<-(randomForest(x,y))
1-sum(y_test==predict(fit,x_test))/length(y_test)
fit
plot(fit)

```

## Regression

You can also embed plots, for example:

```{r readdata}

data<-read.csv("D:/College/DSC640/github/DSC630-1/DSC630/Project/dfAnalysis.csv", header=TRUE)
```

## Regression Formula
```{r reg1}


myfunction <- lm(formula = SalePrice ~ MSSubClass + LotFrontage + LotShape + LandSlope + OverallQual + OverallCond + YearBuilt + YearRemodAdd + MasVnrArea + ExterQual + ExterCond + BsmtQual + BsmtCond + BsmtExposure + BsmtFinType1 + BsmtFinSF1 + BsmtFinType2 + BsmtFinSF2 + BsmtUnfSF + TotalBsmtSF + HeatingQC + CentralAir + X1stFlrSF + X2ndFlrSF + LowQualFinSF + GrLivArea + BsmtFullBath + BsmtHalfBath + FullBath + HalfBath + BedroomAbvGr + KitchenAbvGr + KitchenQual + TotRmsAbvGrd + Functional + Fireplaces + FireplaceQu + GarageYrBlt +     GarageFinish + GarageCars + GarageArea + GarageQual + GarageCond + PavedDrive + WoodDeckSF + OpenPorchSF + EnclosedPorch + X3SsnPorch + ScreenPorch + PoolArea + PoolQC + MiscVal + MoSold + YrSold + MSZoning_FV + MSZoning_RH + MSZoning_RL + MSZoning_RM + Street_Grvl + Street_Pave + Alley_Grvl + Alley_None + Alley_Pave + LandContour_Bnk + LandContour_HLS + LandContour_Low + LandContour_Lvl + Utilities_AllPub, data = data)

summary(myfunction)
```
```{r reg2}


myfunction2 <- lm(formula = SalePrice ~ Utilities_NoSeWa + LotConfig_Corner + LotConfig_CulDSac + LotConfig_FR2 +     LotConfig_FR3 + LotConfig_Inside + Neighborhood_Blmngtn + Neighborhood_Blueste + Neighborhood_BrDale + Neighborhood_BrkSide + Neighborhood_ClearCr + Neighborhood_CollgCr + Neighborhood_Crawfor + Neighborhood_Edwards + Neighborhood_Gilbert + Neighborhood_IDOTRR + Neighborhood_MeadowV + Neighborhood_Mitchel + Neighborhood_NAmes + Neighborhood_NPkVill + Neighborhood_NWAmes + Neighborhood_NoRidge + Neighborhood_NridgHt + Neighborhood_OldTown + Neighborhood_SWISU + Neighborhood_Sawyer + Neighborhood_SawyerW +     Neighborhood_Somerst + Neighborhood_StoneBr + Neighborhood_Timber + Neighborhood_Veenker + Condition1_Artery + Condition1_Feedr + Condition1_Norm + Condition1_PosA + Condition1_PosN + Condition1_RRAe + Condition1_RRAn + Condition1_RRNe + Condition1_RRNn + Condition2_Artery + Condition2_Feedr + Condition2_Norm + Condition2_PosA + Condition2_PosN + Condition2_RRAe + Condition2_RRAn + Condition2_RRNn + BldgType_1Fam + BldgType_2fmCon + BldgType_Duplex + BldgType_Twnhs + BldgType_TwnhsE + HouseStyle_1.5Fin +     HouseStyle_1.5Unf + HouseStyle_1Story + HouseStyle_2.5Fin + HouseStyle_2.5Unf + HouseStyle_2Story + HouseStyle_SFoyer + HouseStyle_SLvl + RoofStyle_Flat + RoofStyle_Gable + RoofStyle_Gambrel + RoofStyle_Hip + RoofStyle_Mansard + RoofStyle_Shed + RoofMatl_ClyTile + RoofMatl_CompShg + RoofMatl_Membran + RoofMatl_Metal + RoofMatl_Roll + RoofMatl_Tar.Grv + RoofMatl_WdShake + RoofMatl_WdShngl + Exterior1st_AsbShng + Exterior1st_AsphShn + Exterior1st_BrkComm + Exterior1st_BrkFace + Exterior1st_CBlock +     Exterior1st_CemntBd + Exterior1st_HdBoard + Exterior1st_ImStucc + Exterior1st_MetalSd + Exterior1st_Plywood + Exterior1st_Stone + Exterior1st_Stucco + Exterior1st_VinylSd + Exterior1st_Wd.Sdng + Exterior1st_WdShing + Exterior2nd_AsbShng + Exterior2nd_AsphShn + Exterior2nd_Brk.Cmn + Exterior2nd_BrkFace + Exterior2nd_CBlock + Exterior2nd_CmentBd + Exterior2nd_HdBoard + Exterior2nd_ImStucc + Exterior2nd_MetalSd + Exterior2nd_Other + Exterior2nd_Plywood + Exterior2nd_Stone + Exterior2nd_Stucco +     Exterior2nd_VinylSd + Exterior2nd_Wd.Sdng + Exterior2nd_Wd.Shng + MasVnrType_BrkCmn + MasVnrType_BrkFace + MasVnrType_None + MasVnrType_Stone + Foundation_BrkTil + Foundation_CBlock + Foundation_PConc + Foundation_Slab + Foundation_Stone + Foundation_Wood + Heating_Floor + Heating_GasA + Heating_GasW + Heating_Grav + Heating_OthW + Heating_Wall + CentralAir_N + CentralAir_Y + Electrical_FuseA + Electrical_FuseF + Electrical_FuseP + Electrical_Mix + Electrical_SBrkr + GarageType_2Types + GarageType_Attchd +     GarageType_Basment + GarageType_BuiltIn + GarageType_CarPort + GarageType_Detchd + GarageType_None + Fence_GdPrv + Fence_GdWo + Fence_MnPrv + Fence_MnWw + Fence_None + MiscFeature_Gar2 + MiscFeature_None + MiscFeature_Othr + MiscFeature_Shed + MiscFeature_TenC + SaleType_COD + SaleType_CWD + SaleType_Con + SaleType_ConLD + SaleType_ConLI + SaleType_ConLw + SaleType_New + SaleType_Oth + SaleType_WD + SaleCondition_Abnorml + SaleCondition_AdjLand + SaleCondition_Alloca + SaleCondition_Family +     SaleCondition_Normal + SaleCondition_Partial, data = data)

summary(myfunction2)
```
Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
```{r reg_final}

myModel <- lm(formula = SalePrice ~ MSSubClass + OverallQual + OverallCond + MasVnrArea + ExterQual + BsmtQual + BsmtCond + BsmtExposure + X1stFlrSF + X2ndFlrSF + BedroomAbvGr + KitchenQual + TotRmsAbvGrd + Functional + GarageCars + + Neighborhood_IDOTRR + Neighborhood_NoRidge + Neighborhood_OldTown + Neighborhood_StoneBr + RoofMatl_ClyTile + RoofMatl_CompShg + RoofMatl_Roll + RoofMatl_Tar.Grv + RoofMatl_WdShake + MasVnrType_BrkFace, data = data)

summary(myModel)
```